org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Identitas publik Android. Ubah sebelum upload pertama ke Play Store.
WEBVIEW_APPLICATION_ID=com.tukugaming.app
WEBVIEW_APP_NAME=TukuGaming
